### ISSUE TITLE
State Backend 

### ISSUE THREAD

**Issue by sarahwooders** [feature-store/ralf#13]
`ralf` currently uses python dictionaries to manage internal state. We should persist state across sessions and allow for flexibility with where features are stored by creating a connector to different state back-ends. 

To start with - probably makes sense to store on SQLLite or on-disk, then can move onto RocksDB/Redis based off what works best for python. We might want to later extend this connector to also work with Feast or other feature stores. 

## Attributes 
- Versioned (i.e. save historical data) vs. not 
- Can combine pre-filled data + updates
    - e.g. if you filled features with your offline pipeline, you can connect to the same `StateConnector`  in the online pipeline to have pre-filled values that continue to be incrementally updated 
    - persistence between runs 
- `StateConnector` should basically replace the internal python dictionary we are using now - so the interface for making tables queryable (adding `.as_queryable(…)`) should stay the same. 

## Object Outline 

```
class StateConnector: 

  def __init__(self, name: str, connection, historical: bool = False): 
    """
    Custom sink that stores 

    :name: Unique handle 
    :connection: Connection to Redis/Hive/Feast/etc. instance to write updates 
    :historical: Whether to store all historical versions (e.g. for an offline store) or the curent version (e.g. for an online store)  
    """
    pass

  def on_record(self, record: Record): 
    self.connection.update(record) 
```

## Example Usage 
```
source_conn = StateConnector(hive_connection, historical=True)
embedding_conn = StateConnector(redis_connection, historical=False) 

source = ralf.from_csv(filename="...", connector=source_conn) 
embeddings = ralf.map(MyOperator, connector=embedding_conn)
```

**Comment by narang-amit** [comment]
Working on this now on my branch (narang-amit/13). 

Made progress towards using SQLite so far

- Defined abstract Connector class (`state-connector/connector.py`) and implemented it with a SQLite connection (`state-connector/sqlite_connector.py`)

Things Left to Do for SQLite MVP

- Modify the abstract class to better abstract DB connections away from user—user should just pass in a connection at one time and we use it for multiple schemas (a la left join)
- How are we generating table names?
- What does keeping historical values look like in practice? Are we always inserting new values into the table rather than updating old ones? If so, what are we using for a key/unique ID? 
- Update the Operator/Operator types to use a Connector 
- Perhaps port over the current TableState class to be a Connector.

Things To Think About

- Right now, we deconstruct a record to store it into a DB and then reconstruct it upon querying. Is that the best solution? Are Records a good/the best medium to use?
- How should we handling metadata—as we get smarter, are we saving more metadata for different policies? Or can we start leveraging the metadata generated/stored by DB's?

**Comment by narang-amit** [comment]
<img width="602" alt="Screen Shot 2022-01-10 at 12 50 21 AM" src="https://user-images.githubusercontent.com/28675329/148723221-10cf3b51-4057-4224-85ed-1a427ae8b0ed.png">

Currently did this approach—you can view the code on my new [branch](https://github.com/feature-store/ralf/tree/narang-amit/13-json/ralf). Still a WIP—need to test more thoroughly but I think this is the bulk of it. 

cc: @sarahwooders @simon-mo

**Comment by narang-amit** [comment]
The current benchmark results (1000 updates):
![Screen Shot 2022-01-18 at 7 31 53 PM](https://user-images.githubusercontent.com/28675329/150058951-b0b127bd-ac62-48c1-87a2-a8e5e2acf327.png)

**Comment by sarahwooders** [comment]
How are you running the benchmark? And what are Rounds/Iterations?

**Comment by narang-amit** [comment]
Sorry, didn't see this—the benchmark is a test I wrote in the PR. You can run it by calling `pytest tests/connector_benchmarks.py`. Rounds/Iterations are syntax from the [pytest-benchmark tool](https://pypi.org/project/pytest-benchmark/).
